#NOTE: Overriding terminal colors
set-option -sa terminal-overrides ",xterm-256color:RGB"

#NOTE: Set other prefix, default = Ctrl + b, and the first window is 1
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
set -g base-index 1
#NOTE: Let you handle text manipulation with VI Motions, and mouse mode 
setw -g mode-keys vi 
set -g mouse on

#NOTE: Sets the status bar at the top
set-option -g status-position top

#NOTE: Movement between windows, is equal to "ALT + h/l"
bind -n M-h previous-window 
bind -n M-l next-window

set -g @plugin "tmux-plugins/tpm"

#TODO: SEE WHAT THIS DOES BUT IT FIXED SOME QUIRKS WITH BASE TMUX CONFIG
set -g @plugin "tmux-plugins/tmux-sensible" 

#NOTE: THIS IS FOR THE MOVEMENT BETWEEN NEOVIM AND TMUX
set -g @plugin "christoomey/vim-tmux-navigator" 

# COLORSCHEME
# set -g @plugin "janoamaral/tokyo-night-tmux"

######################
#https://github.com/fabioluciano/tmux-powerkit?tab=readme-ov-file
set -g @plugin "fabioluciano/tmux-powerkit"

# GPU #
set -g @powerkit_plugin_gpu_icon "󰢮"

set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant 'night'
set -g @powerkit_plugins "datetime,battery,cpu,gpu,memory"

# Auto-detect OS icon
set -g @powerkit_session_icon 'auto'
######################

run "~/.tmux/plugins/tpm/tpm"
