-- PRUEBA
-- lazy.nvim - PLUGIN MANAGER
-- 'lewis6991/gitsigns.nvim', - COSAS DE GIT
-- 'folke/which-key.nvim', - VER LAS POSIBLES COMBINACIONES DE TECLAS QUE TIENES
-- 'nvim-telescope/telescope.nvim', - VIM TELESCOPE CREO QUE ES PARA BUSCAR ARCHIVOS Y DE TODO
--
-- NOTE: COSAS DEL LSP
--
-- 'folke/lazydev.nvim',
-- 'neovim/nvim-lspconfig',
--
-- 'stevearc/conform.nvim', - AUTOFORMATO
-- 'saghen/blink.cmp', - AUTOCOMPLETADO
--
-- 'folke/tokyonight.nvim', - COLOR GUAPO
-- 'folke/todo-comments.nvim', - COMENTARIOS CON COLORES
-- 'echasnovski/mini.nvim', - COLECCION DE ALGUNOS PLUGINS PEQUEÑITOS
-- 'nvim-treesitter/nvim-treesitter', - TREESITTER
