-- LOT OF QUALITY OF LIFE ADDONS

local function load_dashboard()
	local dashboard = require("plugins.snacks.dashboard")
	return vim.tbl_extend("force", dashboard.init(), dashboard.opts())
end

return {
	'folke/snacks.nvim',
	priority = 1000,
	lazy = false,
	---@type snacks.Config
	opts = {
		bigfile = { enabled = true },   -- A better way to deal with big files
		bufdelete = { enabled = true }, -- Lets you delete buffers without disrupting window layout
		dashboard = load_dashboard(),   -- What shows up when opening nvim
		explorer = require 'plugins.snacks.explorer', -- A file explorer
		indent = { enabled = true },    -- Indent guides and scopes
		input = { enabled = false },    -- Better vim.ui.input
		picker = { enabled = false },   -- PENSARME SI USAR ESTE PICKER O EL DE SIEMPRE
		notifier = { enabled = true },  -- Pretty vim.notify FIX: NOICE IS FOR THAT NO?
		quickfile = { enabled = true }, -- When entering a file with nvim file_name, it will load as quick as posible
		scope = { enabled = false },    -- Scope detection text objects and jumping based on treesitter or indent
		scroll = { enabled = true },    -- Smooth scrolling
		statuscolumn = { enabled = true }, -- Pretty status column
		words = { enabled = true },     -- Auto show LSP  references and quickly navigate between them
		terminal = require 'plugins.snacks.terminal', -- WARN: DISABLED FOR NOW
	},
	keys = vim.list_extend(require 'config.keymaps.snacks.terminal', {}),
}

--     {
--       '<leader>:',
--       function()
--         Snacks.picker.command_history()
--       end,
--       desc = 'Command History',
--     },
--     {
--       '<leader>e',
--       function()
--         Snacks.explorer()
--       end,
--       desc = 'File Explorer',
--     },
--     PERF: QUE COJONES ES PICKER
--     TODO: GOOD IDEA BUT BETTER IF TELESCOPE
--     {
--       '<leader>fp',
--       function()
--         Snacks.picker.projects()
--       end,
--       desc = 'Projects',
--     },
--     {
--       '<leader>fr',
--       function()
--         Snacks.picker.recent()
--       end,
--       desc = 'Recent',
--     },


-- return {
--   'folke/snacks.nvim',
--   priority = 1000,
--   lazy = false,
--   ---@type snacks.Config
--   opts = {
--     bigfile = { enabled = true },
--     dashboard = { enabled = true },
--     explorer = { enabled = true },
--     indent = { enabled = true },
--     input = { enabled = true },
--     notifier = {
--       enabled = true,
--       timeout = 3000,
--     },
--     picker = { enabled = true },
--     quickfile = { enabled = true },
--     scope = { enabled = true },
--     scroll = { enabled = true },
--     statuscolumn = { enabled = true },
--     words = { enabled = true },
--     styles = {
--       notification = {
--         -- wo = { wrap = true } -- Wrap notifications
--       },
--     },
--   },
--   keys = {
--     -- Top Pickers & Explorer
--     {
--       '<leader><space>',
--       function()
--         Snacks.picker.smart()
--       end,
--       desc = 'Smart Find Files',
--     },
--     {
--       '<leader>,',
--       function()
--         Snacks.picker.buffers()
--       end,
--       desc = 'Buffers',
--     },
--     {
--       '<leader>/',
--       function()
--         Snacks.picker.grep()
--       end,
--       desc = 'Grep',
--     },
--     {
--       '<leader>:',
--       function()
--         Snacks.picker.command_history()
--       end,
--       desc = 'Command History',
--     },
--     {
--       '<leader>n',
--       function()
--         Snacks.picker.notifications()
--       end,
--       desc = 'Notification History',
--     },
--     {
--       '<leader>e',
--       function()
--         Snacks.explorer()
--       end,
--       desc = 'File Explorer',
--     },
--     -- find
--     {
--       '<leader>fb',
--       function()
--         Snacks.picker.buffers()
--       end,
--       desc = 'Buffers',
--     },
--     {
--       '<leader>fc',
--       function()
--         Snacks.picker.files { cwd = vim.fn.stdpath 'config' }
--       end,
--       desc = 'Find Config File',
--     },
--     {
--       '<leader>ff',
--       function()
--         Snacks.picker.files()
--       end,
--       desc = 'Find Files',
--     },
--     {
--       '<leader>fg',
--       function()
--         Snacks.picker.git_files()
--       end,
--       desc = 'Find Git Files',
--     },
--     {
--       '<leader>fp',
--       function()
--         Snacks.picker.projects()
--       end,
--       desc = 'Projects',
--     },
--     {
--       '<leader>fr',
--       function()
--         Snacks.picker.recent()
--       end,
--       desc = 'Recent',
--     },
--     -- git
--     {
--       '<leader>gb',
--       function()
--         Snacks.picker.git_branches()
--       end,
--       desc = 'Git Branches',
--     },
--     {
--       '<leader>gl',
--       function()
--         Snacks.picker.git_log()
--       end,
--       desc = 'Git Log',
--     },
--     {
--       '<leader>gL',
--       function()
--         Snacks.picker.git_log_line()
--       end,
--       desc = 'Git Log Line',
--     },
--     {
--       '<leader>gs',
--       function()
--         Snacks.picker.git_status()
--       end,
--       desc = 'Git Status',
--     },
--     {
--       '<leader>gS',
--       function()
--         Snacks.picker.git_stash()
--       end,
--       desc = 'Git Stash',
--     },
--     {
--       '<leader>gd',
--       function()
--         Snacks.picker.git_diff()
--       end,
--       desc = 'Git Diff (Hunks)',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>gf',
--       function()
--         Snacks.picker.git_log_file()
--       end,
--       desc = 'Git Log File',
--     },
--     -- gh
--     TODO: INTERESTING
--     {
--       '<leader>gi',
--       function()
--         Snacks.picker.gh_issue()
--       end,
--       desc = 'GitHub Issues (open)',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>gI',
--       function()
--         Snacks.picker.gh_issue { state = 'all' }
--       end,
--       desc = 'GitHub Issues (all)',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>gp',
--       function()
--         Snacks.picker.gh_pr()
--       end,
--       desc = 'GitHub Pull Requests (open)',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>gP',
--       function()
--         Snacks.picker.gh_pr { state = 'all' }
--       end,
--       desc = 'GitHub Pull Requests (all)',
--     },
--     TODO: INTERESTING
--     -- Grep
--     {
--       '<leader>sb',
--       function()
--         Snacks.picker.lines()
--       end,
--       desc = 'Buffer Lines',
--     },
--     {
--       '<leader>sB',
--       function()
--         Snacks.picker.grep_buffers()
--       end,
--       desc = 'Grep Open Buffers',
--     },
--     {
--       '<leader>sg',
--       function()
--         Snacks.picker.grep()
--       end,
--       desc = 'Grep',
--     },
--     {
--       '<leader>sw',
--       function()
--         Snacks.picker.grep_word()
--       end,
--       desc = 'Visual selection or word',
--       mode = { 'n', 'x' },
--     },
--     -- search
--     {
--       '<leader>s"',
--       function()
--         Snacks.picker.registers()
--       end,
--       desc = 'Registers',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>s/',
--       function()
--         Snacks.picker.search_history()
--       end,
--       desc = 'Search History',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>sa',
--       function()
--         Snacks.picker.autocmds()
--       end,
--       desc = 'Autocmds',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>sb',
--       function()
--         Snacks.picker.lines()
--       end,
--       desc = 'Buffer Lines',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>sc',
--       function()
--         Snacks.picker.command_history()
--       end,
--       desc = 'Command History',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>sC',
--       function()
--         Snacks.picker.commands()
--       end,
--       desc = 'Commands',
--     },
--     TODO: INTERESTING MAYBE BETTER THAN LEADER OD
--     {
--       '<leader>sd',
--       function()
--         Snacks.picker.diagnostics()
--       end,
--       desc = 'Diagnostics',
--     },
--     {
--       '<leader>sD',
--       function()
--         Snacks.picker.diagnostics_buffer()
--       end,
--       desc = 'Buffer Diagnostics',
--     },
--     {
--       '<leader>sh',
--       function()
--         Snacks.picker.help()
--       end,
--       desc = 'Help Pages',
--     },
--     {
--       '<leader>sH',
--       function()
--         Snacks.picker.highlights()
--       end,
--       desc = 'Highlights',
--     },
--     {
--       '<leader>si',
--       function()
--         Snacks.picker.icons()
--       end,
--       desc = 'Icons',
--     },
--     {
--       '<leader>sj',
--       function()
--         Snacks.picker.jumps()
--       end,
--       desc = 'Jumps',
--     },
--     {
--       '<leader>sk',
--       function()
--         Snacks.picker.keymaps()
--       end,
--       desc = 'Keymaps',
--     },
--     {
--       '<leader>sl',
--       function()
--         Snacks.picker.loclist()
--       end,
--       desc = 'Location List',
--     },
--     {
--       '<leader>sm',
--       function()
--         Snacks.picker.marks()
--       end,
--       desc = 'Marks',
--     },
--     {
--       '<leader>sM',
--       function()
--         Snacks.picker.man()
--       end,
--       desc = 'Man Pages',
--     },
--     {
--       '<leader>sp',
--       function()
--         Snacks.picker.lazy()
--       end,
--       desc = 'Search for Plugin Spec',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>sq',
--       function()
--         Snacks.picker.qflist()
--       end,
--       desc = 'Quickfix List',
--     },
--     TODO: INTERESTING WHAT DOES IT MEAN BY RESUME
--     {
--       '<leader>sR',
--       function()
--         Snacks.picker.resume()
--       end,
--       desc = 'Resume',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>su',
--       function()
--         Snacks.picker.undo()
--       end,
--       desc = 'Undo History',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>uC',
--       function()
--         Snacks.picker.colorschemes()
--       end,
--       desc = 'Colorschemes',
--     },
--     -- LSP
--     {
--       'gd',
--       function()
--         Snacks.picker.lsp_definitions()
--       end,
--       desc = 'Goto Definition',
--     },
--     {
--       'gD',
--       function()
--         Snacks.picker.lsp_declarations()
--       end,
--       desc = 'Goto Declaration',
--     },
--     {
--       'gr',
--       function()
--         Snacks.picker.lsp_references()
--       end,
--       nowait = true,
--       desc = 'References',
--     },
--     {
--       'gI',
--       function()
--         Snacks.picker.lsp_implementations()
--       end,
--       desc = 'Goto Implementation',
--     },
--     {
--       'gy',
--       function()
--         Snacks.picker.lsp_type_definitions()
--       end,
--       desc = 'Goto T[y]pe Definition',
--     },
--     {
--       'gai',
--       function()
--         Snacks.picker.lsp_incoming_calls()
--       end,
--       desc = 'C[a]lls Incoming',
--     },
--     {
--       'gao',
--       function()
--         Snacks.picker.lsp_outgoing_calls()
--       end,
--       desc = 'C[a]lls Outgoing',
--     },
--     {
--       '<leader>ss',
--       function()
--         snacks.picker.lsp_symbols()
--       end,
--       desc = 'LSP Symbols',
--     },
--     {
--       '<leader>sS',
--       function()
--         Snacks.picker.lsp_workspace_symbols()
--       end,
--       desc = 'LSP Workspace Symbols',
--     },
--     TODO: INTERESTING
--     -- Other
--     {
--       '<leader>z',
--       function()
--         Snacks.zen()
--       end,
--       desc = 'Toggle Zen Mode',
--     },
--     TODO: INTERESTING
--     {
--       '<leader>Z',
--       function()
--         Snacks.zen.zoom()
--       end,
--       desc = 'Toggle Zoom',
--     },
--     TODO: WHAT IS SCRATCH
--     {
--       '<leader>.',
--       function()
--         Snacks.scratch()
--       end,
--       desc = 'Toggle Scratch Buffer',
--     },
--     {
--       '<leader>S',
--       function()
--         Snacks.scratch.select()
--       end,
--       desc = 'Select Scratch Buffer',
--     },
--     {
--       '<leader>n',
--       function()
--         Snacks.notifier.show_history()
--       end,
--       desc = 'Notification History',
--     },
--     {
--       '<leader>bd',
--       function()
--         Snacks.bufdelete()
--       end,
--       desc = 'Delete Buffer',
--     },
--     {
--       '<leader>cR',
--       function()
--         Snacks.rename.rename_file()
--       end,
--       desc = 'Rename File',
--     },
--     {
--       '<leader>gB',
--       function()
--         Snacks.gitbrowse()
--       end,
--       desc = 'Git Browse',
--       mode = { 'n', 'v' },
--     },
--     {
--       '<leader>gg',
--       function()
--         Snacks.lazygit()
--       end,
--       desc = 'Lazygit',
--     },
--     {
--       '<leader>un',
--       function()
--         Snacks.notifier.hide()
--       end,
--       desc = 'Dismiss All Notifications',
--     },
--     {
--       ']]',
--       function()
--         Snacks.words.jump(vim.v.count1)
--       end,
--       desc = 'Next Reference',
--       mode = { 'n', 't' },
--     },
--     {
--       '[[',
--       function()
--         Snacks.words.jump(-vim.v.count1)
--       end,
--       desc = 'Prev Reference',
--       mode = { 'n', 't' },
--     },
--     {
--       '<leader>N',
--       desc = 'Neovim News',
--       function()
--         Snacks.win {
--           file = vim.api.nvim_get_runtime_file('doc/news.txt', false)[1],
--           width = 0.6,
--           height = 0.6,
--           wo = {
--             spell = false,
--             wrap = false,
--             signcolumn = 'yes',
--             statuscolumn = ' ',
--             conceallevel = 3,
--           },
--         }
--       end,
--     },
--   },
--   init = function()
--     vim.api.nvim_create_autocmd('User', {
--       pattern = 'VeryLazy',
--       callback = function()
--         -- Setup some globals for debugging (lazy-loaded)
--         _G.dd = function(...)
--           Snacks.debug.inspect(...)
--         end
--         _G.bt = function()
--           Snacks.debug.backtrace()
--         end
--
--         -- Override print to use snacks for `:=` command
--         if vim.fn.has 'nvim-0.11' == 1 then
--           vim._print = function(_, ...)
--             dd(...)
--           end
--         else
--           vim.print = _G.dd
--         end
--
--         -- Create some toggle mappings
--         Snacks.toggle.option('spell', { name = 'Spelling' }):map '<leader>us'
--         Snacks.toggle.option('wrap', { name = 'Wrap' }):map '<leader>uw'
--         Snacks.toggle.option('relativenumber', { name = 'Relative Number' }):map '<leader>uL'
--         Snacks.toggle.diagnostics():map '<leader>ud'
--         Snacks.toggle.line_number():map '<leader>ul'
--         Snacks.toggle.option('conceallevel', { off = 0, on = vim.o.conceallevel > 0 and vim.o.conceallevel or 2 }):map '<leader>uc'
--         Snacks.toggle.treesitter():map '<leader>uT'
--         Snacks.toggle.option('background', { off = 'light', on = 'dark', name = 'Dark Background' }):map '<leader>ub'
--         Snacks.toggle.inlay_hints():map '<leader>uh'
--         Snacks.toggle.indent():map '<leader>ug'
--         Snacks.toggle.dim():map '<leader>uD'
--       end,
--     })
--   end,
-- }
